### PR TITLE
Refactory the code

### PR DESCRIPTION
**Pull request by hlxwell**

### CODE REVIEW

**Comment by jct808** [comment]
Thanks, Michael.

**Comment by hlxwell** [comment]
Just saw you applied Odigo's job, then checking your code quality. so do
you have any other better code sample you made?

On Thu, Jul 9, 2015 at 7:30 PM, Chris Tai notifications@github.com wrote:

> Thanks, Michael.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jct808/chinese_numbers_characters_converter/pull/1#issuecomment-119903545
> .

## 

Best Regards
From Michael He

**Comment by jct808** [comment]
I see, thanks… 
As my resume mention, I just left the furniture business, and want to be a full time programmer.
Not so much code can show you. 
Here is my Bitbucket link, which I get a case for Hotel. 
https://bitbucket.org/jct808/hotel_app https://bitbucket.org/jct808/hotel_app

Best Regards
Chris

**Comment by hlxwell** [comment]
I saw your code, so I also knows you may not working on Rails for too long. 
- do you like Japan Travel industry?
- do you have frontend development experience?
- do you have any linux knowledge?

**Comment by jct808** [comment]
Hi, Michael

```
Yes, I do not write Rails so long, but writing code is a hobby for me, if I can make it as my job, it will be great.
```

Yes, I do. I go back to Japan once of one year with my wife, She is a Japanese. I think Japanese travelling business will be great, not only 2016 Olympic game but also comic culture. 
Actual, not really. But if you are talking about Bootstrap, jQuery, CSS or javascript. I have knowledge about them, I am studying AngularJS now. But I don’t any idea about coffeeScript. if needs, I can  study about it. I am not afraid to learn new language at all. 
My University is teaching UNIX base (Sun Solars), I am using a mac since studying. so most of knowledge about linux I am familiar with. 

I wrote another code about translation via using google api. (https://github.com/jct808/get_google_translate https://github.com/jct808/get_google_translate) https://rubygems.org/gems/get_google_translate https://rubygems.org/gems/get_google_translate ( Gemfile )

Best Regards
Chris Tai

**Comment by hlxwell** [comment]
sorry for this kind of unoffical talk, but thank you very much to answer my questions.
So let's have a skype interview then.
Please give me your skype id and tell me when do you have time to have a interview.

**Comment by jct808** [comment]
Dear Michael, 

It’s fine for me, I am very glad to talk with you. 
My Skype account is: tai_tw
Tomorrow afternoon I will have free time to have interview, what time would you like to have it? There is one hour difference between Taiwan and Japan. 
How about at 4pm in Japan ( 3pm Taiwan ) Tomorrow?
If you are not fine with it, please tell me about when you would like to have a interivew ? I can try to make it. 

Best Regards
Chris Tai

**Pull request merged**
